### ISSUE TITLE
The signInWithPopup doesn't work

### ISSUE THREAD

**Issue by retro-sapphire** [fireship-io/react-firebase-chat#13]
Hey fireship-io, The signInWithPopup() function doesn't work, please help, thanks!

**Comment by wetech16** [comment]
Check 1. your firebase-authentication-signin method: set google sign in able
check 2. firebase-authentication -  signin method : add Authorized domains

**Comment by retro-sapphire** [comment]
Oh I forgot to add authorized domains, thanks
