### ISSUE TITLE
unable to access "firebase/app" when firebase module is updated

### ISSUE THREAD

**Issue by amar-jay** [fireship-io/react-firebase-chat#31]
Could you assist 
this is my first time trying firebase
Im unable to access, "firebase/app";
whenever I create import from firebase/app

**Comment by Sanchitbajaj02** [comment]
instead of using 
```react
import firebase from "firebase/app";
```
use

```react
import firebase from "firebase/compact/app";
```

**Comment by JonasPetri** [comment]
> instead of using
> 
> ```
> import firebase from "firebase/app";
> ```
> 
> use
> 
> ```
> import firebase from "firebase/compact/app";
> ```

Yep that is what you should do, a small typo though, it should be "firebase/compat/app".

**Comment by Kenramiscal1106** [comment]
> Could you assist this is my first time trying firebase Im unable to access, "firebase/app"; whenever I create import from firebase/app

you can't import firebase/app in version 9 sdk. Since this version uses modular sdk (which supports tree shaking), you must use "firebase/compat/app". This also applies to firebase/firestore -> firebase/compat/firestore & other firebase tools

**Comment by richardHaggioGwati** [comment]
If you take a little pick inside the node_modules/firebase/package.json you will see that is supposed to be
```
import firebase from "firebase/compat/app":
```
**NOT** 
```
import firebase from "firebase/compact/app";
```
