### ISSUE TITLE
Auto ban after 7 messages

### ISSUE THREAD

**Issue by Paultje52** [fireship-io/react-firebase-chat#5]
Idk why, but I got banned. I joked a bit and then I coudn't send any messages. My last message was "Likely, yeah". I recorded it and I pasted the recording in this zip.
[Video.zip](https://github.com/fireship-io/react-firebase-chat/files/5278712/Video.zip)

I don't care if I can't chat anymore, but I think it's odd that you randomly get banned, even when you didn't swear.

**Comment by chmus** [comment]
Same

**Comment by Paultje52** [comment]
I think the problem is in [bad-words](https://npmjs.com/bad-words).  Maybr something like a warning system would be nice. Like when you swear three times, you get muted for like half an hour. When you swear again, it's for an hour, then 2, etc.

I think that the warning system would be nice for false flags.

It should still convert your message with the ***

**Comment by chmus** [comment]
But, all of these would make project unnecessarily complicated. The purpose is to just show how React and Firestore can be used together. Am I wrong?

**Comment by hakanrw** [comment]
You can send maximum of 7 messages, check the [index.js](https://github.com/fireship-io/react-firebase-chat/blob/master/functions/index.js).

**Comment by Paultje52** [comment]
Why would you want to set a limit? Something like a rate limit, so you can send a couple messages per minute or something like that is understandable, but limiting how many messages you can send in total isn't.

**Comment by hakanrw** [comment]
I agree, it was annoying to get banned for something like this when I was talking. 
Fireship was probably too lazy to implement a time limit and gave this answer xD
![image](https://user-images.githubusercontent.com/57678928/94367016-70350b00-00e4-11eb-8356-70319b11f1fc.png)

**Comment by Paultje52** [comment]
I think I'll make a pull request for a simple rate limit thing

**Comment by saikrishnadas** [comment]
Remove the few last lines of code and you have no limit. 


```
const functions = require("firebase-functions");

const Filter = require("bad-words");

const admin = require("firebase-admin");
admin.initializeApp();

const db = admin.firestore();

exports.detectEvilUsers = functions.firestore
  .document("messages/{msgId}")
  .onCreate(async (doc, ctx) => {
    const filter = new Filter();
    const { text, uid } = doc.data();

    if (filter.isProfane(text)) {
      const cleaned = filter.clean(text);
      await doc.ref.update({
        text: "I got banned for lifetime for using voilated words",
      });

      await db.collection("banned").doc(uid).set({});
    }
  });
```
