### ISSUE TITLE
Only showing 25 messeges

### ISSUE THREAD

**Issue by Oshanwick** [fireship-io/react-firebase-chat#8]
My app Only showing 25 messeges.then,when i type messege its not showing in ui.but its goes to database

**Comment by klutchdev** [comment]
**Works as designed**

Adjust the limiter. Also, read your code a couple times before firing issue tickets off lol

🔥🔥🔥

```jsx
const ChatRoom = () => {
  const dummy = useRef();
  const messagesRef = firestore.collection('messages');

  const query = messagesRef.orderBy('createdAt').limit(25); // ← This is the value you'd adjust for limiting.
  const [messages] = useCollectionData(query, { idField: 'id' });
```

![limit25](https://user-images.githubusercontent.com/58617435/94984122-be983e80-0516-11eb-9ce5-61a932ff5a3f.png)
